spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_case_payment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111

decorator:
  datasource:
    p6spy:
      enable-logging: true